version: '3'

services:
  SML_Enviorment:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sml
    container_name: sml
    networks:
      - primary
    volumes:
      - ../Ml_Files:/Ml_Files
    command: /start

networks:
  primary:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"